= Metanorma-CLI single executable binary

image:https://github.com/metanorma/packed-mn/workflows/linux/badge.svg["Build Status", link="https://github.com/metanorma/packed-mn/actions?workflow=linux"]
image:https://github.com/metanorma/packed-mn/workflows/macos/badge.svg["Build Status", link="https://github.com/metanorma/packed-mn/actions?workflow=macos"]
image:https://github.com/metanorma/packed-mn/workflows/windows/badge.svg["Build Status", link="https://github.com/metanorma/packed-mn/actions?workflow=windows"]


== Purpose

Metanorma is a sophisticated document publishing tool for
standardization bodies.
It is written in Ruby with a number of dependencies.

User organizations of Metanorma run on multiple platforms,
including Windows, Linux and macOS.

The challenge is how to ensure the distribution and installation of
Metanorma works on the target system reliably.

Today, Metanorma offers:

* Ruby gem
* Linux setup script
* macOS Homebrew package
* Windows Chocolatey package
* Docker container

However, all these packages require a long installation process
with caveats, such as being prone to network failures and a network
of dependencies to install.

This repo attempts to package dependencies using `ruby-packer`, a
tool that packages a Ruby interpreter with gems and dependencies
into a RAM disk.

Our goal is to make installation quick and dependable for our users.


== Usage

=== Compile executable

For macOS / Linux:

[source,sh]
----
$: make build
----

For Windows:

[source,batch]
----
$: make -f Makefile.win build
----

This will clear `build/` folder files and compile a new version
from the `metanorma_entry_point` Ruby script.

=== Icon file for windows

Icon can be updated with `make png2ico` with use `imagemagick` under the hood

== metanorma_entry_point

This script loads all dependencies in order to ruby packer
correctly link all gems and their native extensions.
