:sectnums:
== Specifications

=== General, organoleptic and health characteristics

Kernels of rice, whether parboiled, husked or milled, and whether whole or broken, shall be sound, clean and free from foreign odours or odour which indicates deterioration.

The levels of additives and pesticide residues and other contaminants shall not exceed the maximum limits permitted in the country of destination.

The presence of living insects which are visible to the naked eye is not permitted. This should be determined before separating the bulk sample into test samples.

=== Physical and chemical characteristics

==== {blank}

The mass fraction of moisture, determined in accordance with <<ISO712>>, using an oven complying with the requirements of <<IEC61010-2>>, shall not be greater than 15 %.footnote:[Formerly denoted as 15 % (m/m).]

The mass fraction of extraneous matter and defective kernels in husked and milled rice, whether or not parboiled, determined in accordance with <<AnnexA>>, shall not be greater than the values specified in <<table1>>.

NOTE: Lower mass fractions of moisture are sometimes needed for certain destinations depending on the climate, duration of transport and storage. For further details, see <<ISO6322-1>>, <<ISO6322-2>> and <<ISO6322-3>>.

==== {blank}

The defect tolerance for the categories considered, and determined in accordance with the method given in <<AnnexA>>, shall not exceed the limits given in <<table1>>.

[#table1]
[cols="<,^,^,^,^",options="header,footer",headerrows=2]
.Maximum permissible mass fraction of defects
|===
.2+|Defect 4+^| Maximum permissible mass fraction of defects in husked rice +
stem:[w_max]
| in husked rice | in milled rice (non-glutinous) | in husked parboiled rice | in milled parboiled rice

| Extraneous matter: organic footnote:[Organic extraneous matter includes foreign seeds, husks, bran, parts of straw, etc.] | 1,0 | 0,5 | 1,0 | 0,5
// not rendered list here
| Extraneous matter: inorganic footnote:[Inorganic extraneous matter includes stones, sand, dust, etc.] | 0,5 | 0,5 | 0,5 | 0,5
| Paddy | 2,5 | 0,3 | 2,5 | 0,3
| Husked rice, non-parboiled | Not applicable | 1,0 | 1,0 | 1,0
| Milled rice, non-parboiled | 1,0 | Not applicable | 1,0 | 1,0
| Husked rice, parboiled | 1,0 | 1,0 | Not applicable | 1,0
| Milled rice, parboiled | 1,0 | 1,0 | 1,0 | Not applicable
| Chips | 0,1 | 0,1 | 0,1 | 0,1
| HDK | 2,0 footnoteref:[defectsmass,The maximum permissible mass fraction of defects shall be determined with respect to the mass fraction obtained after milling.] | 2,0 | 2,0 footnoteref:[defectsmass] | 2,0
| Damaged kernels | 4,0 | 3,0 | 4,0 | 3,0
| Immature and/or malformed kernels | 8,0 | 2,0 | 8,0 | 2,0
| Chalky kernels | 5,0 footnoteref:[defectsmass] | 5,0 | Not applicable | Not applicable
| Red kernels and red-streaked kernels | 12,0 | 12,0 | 12,0 footnoteref:[defectsmass] | 12,0
| Partly gelatinized kernels | Not applicable | Not applicable | 11,0 footnoteref:[defectsmass] | 11,0
| Pecks | Not applicable | Not applicable | 4,0 | 2,0
| Waxy rice | 1,0 footnoteref:[defectsmass] | 1,0 | 1,0 footnoteref:[defectsmass] | 1,0

5+a| Live insects shall not be present. Dead insects shall be included in extraneous matter.
|===

NOTE: This table is based on <<ISO7301,table 1>>.

NOTE: Some commercial contracts require information in addition to that provided in this table.

NOTE: Only full red husked (cargo) rice is considered in this table.

