[[AnnexB]]
[appendix,obligation=informative]
== Determination of the waxy rice content of parboiled rice

=== Principle

Waxy rice kernels have a reddish brown colour when stained in an iodine solution, while non-waxy rice kernels show a dark blue colour.

=== Apparatus

The usual laboratory apparatus and, in particular, the following.

[%inline-header]
[[AnnexB-2-1]]
==== Balance,

capable of weighing to the nearest 0,01 g.

[%inline-header]
[[AnnexB-2-2]]
==== Glass beaker,

of capacity 250 ml.

[%inline-header]
[[AnnexB-2-3]]
==== Small white colour bowls,

or any white colour container of a suitable size.

[%inline-header]
[[AnnexB-2-4]]
==== Wire sieve,

with long rounded apertures of (1 mm stem:[{:(+0.02),(0):}] mm) &times; (20 mm stem:[{:(+2),(-1):}] mm).

[%inline-header]
[[AnnexB-2-5]]
==== Stirrer rod.

[%inline-header]
[[AnnexB-2-6]]
==== Tweezers or forceps.

[%inline-header]
[[AnnexB-2-7]]
==== Tissue paper.

===  Reagents

WARNING: Direct contact of iodine with skin can cause lesions so care should be taken in handling iodine. Iodine vapour is very irritating to eyes and mucous membranes.

[%inline-header]
[[AnnexB-3-1]]
==== Deionized water,

Grade 3 quality as specified in <<ISO3696>>.

[%inline-header]
[[AnnexB-3-2]]
==== Iodine stock solution,

containing a mass fraction of 4,1 % iodine and 6,3 % potassium iodide in deionized water such as Lugols.footnote:[Lugols is an example of a suitable product available commercially. This information is given for the convenience of users of this document and does not constitute an endorsement by ISO of this product.]

[%inline-header]
[[AnnexB-3-3]]
==== Iodine working solution,

obtained by diluting the stock solution (<<AnnexB-3-2>>) two times (by volume) with deionized water (<<AnnexB-3-1>>).

Prepare fresh daily.

=== Sampling

Sampling shall be carried out in accordance with <<clause5>>.

=== Determination

==== {blank}
Weigh a portion of about 100 g of milled rice and put it into a glass beaker (<<AnnexB-2-2>>).

==== {blank}
Add enough iodine working solution (<<AnnexB-3-3>>) to soak the kernels, and stir (<<AnnexB-2-5>>) until all the kernels are submerged under the solution. Let the kernels soak in the solution for 30 s.

==== {blank}
Pour the rice and solution into a wire sieve (<<AnnexB-2-4>>), and shake the basket slightly in order to drain out the solution. Then place the wire sieve on a piece of tissue paper (<<AnnexB-2-7>>) to absorb the excess liquid.

==== {blank}
Pour the stained kernels into a bowl (<<AnnexB-2-3>>). Using tweezers or forceps (<<AnnexB-2-6>>), separate the reddish brown kernels of waxy rice from the dark blue kernels of non-waxy rice.

==== {blank}
Weigh the waxy rice portion (stem:[m_1]) and the non-waxy rice portion (stem:[m_2]) to the nearest 0,1 g.

=== Calculation

Calculate the mass fraction, expressed as a percentage, of the waxy rice, stem:[w_(wax)], using <<formulaB-1>>:

[[formulaB-1,B.1]]
[stem]
++++
w_(wax) = (m_1) / (m_1 + m_2) xx 100
++++

where

stem:[m_1]:: is the mass, expressed in grams, of the waxy rice portion;
stem:[m_2]:: is the mass, expressed in grams, of the non-waxy rice portion.

=== Test report

Report the results as specified in <<clause7>>, giving the results calculated using <<formulaB-1>>.

