name: release-tag

on:
  repository_dispatch:
    types: [ metanorma/metanorma-cli ]

jobs:
  push-tag:
    runs-on: ubuntu-18.04
    if: startsWith(github.event.client_payload.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}

    - name: Parse metanorma-cli version
      env:
        METANORMA_CLI_TAG: ${{ github.event.client_payload.ref }}
      run: |
        echo METANORMA_CLI_VERSION=${METANORMA_CLI_TAG#*/v} >> ${GITHUB_ENV}

    - uses: metanorma/metanorma-build-scripts/gh-rubygems-setup-action@main
      with:
        token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.5
        bundler: 2.2.3

    - run: gem install bundler

    - name: Update version
      run: |
        bundle remove metanorma-cli
        bundle add metanorma-cli -v ${METANORMA_CLI_VERSION}
        bundle install --deployment

    - name: Push commit and tag
      run: |
        git config --global user.name "metanorma-ci"
        git config --global user.email "metanorma-ci@users.noreply.github.com"
        git add Gemfile
        git commit -m "Bump version to ${METANORMA_CLI_VERSION}"
        git tag v${METANORMA_CLI_VERSION}
        git push origin HEAD:${GITHUB_REF} --tags
