name: release

on:
  repository_dispatch:
    types: [ metanorma/metanorma-cli ]

jobs:
  build_linux:
    runs-on: ubuntu-18.04
    if: startsWith(github.event.client_payload.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v1
    - name: Add writable remote
      run: |
        git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
        git pull github ${GITHUB_REF} --ff-only
    - name: Parse metanorma-cli version
      env:
        METANORMA_CLI_TAG: ${{ github.event.client_payload.ref }}
      run: |
        echo "::set-env name=METANORMA_CLI_VERSION::${METANORMA_CLI_TAG#*/v}"
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: Install bundler
      run: |
        gem install bundler
    - name: Update version
      run: |
        bundle remove metanorma-cli
        bundle add metanorma-cli -v ${METANORMA_CLI_VERSION}
    - name: Push commit and tag
      run: |
        git add Gemfile Gemfile.lock
        git commit -m "Bump version to ${METANORMA_CLI_VERSION}"
        git tag v${METANORMA_CLI_VERSION}
        git push github HEAD:${GITHUB_REF} --tags